apiVersion: v1
kind: Pod
metadata:
  name: placeholder-pod
spec:
  containers:
    - name: hello
      image: photon
      command: [ "/bin/sh", "-c", "sleep 600000" ]
      resources:
        requests:
          cpu: 1200m
          memory: 418Mi
  restartPolicy: Never